project_id = "jafaukblhxbycjzrbkeq"

[functions.upload-bill]
verify_jwt = false

[functions.submit-form]
verify_jwt = false

[functions.get-analysis]
verify_jwt = false

[functions.check-status]
verify_jwt = false

[functions.get-full-result]
verify_jwt = false

[functions.save-dispute-letter]
verify_jwt = false

[functions.search-cities]
verify_jwt = false