project_id = "jafaukblhxbycjzrbkeq"

[functions.analyze-bill-lovable]
verify_jwt = false

[functions.n8n-api]
verify_jwt = false

[functions.submit-form]
verify_jwt = false

[functions.get-analysis]
verify_jwt = false

[functions.check-status]
verify_jwt = false

[functions.get-full-result]
verify_jwt = false

[functions.save-dispute-letter]
verify_jwt = false

[functions.search-cities]
verify_jwt = false

[functions.generate-pdf-report]
verify_jwt = false

[functions.generate-dispute-letter]
verify_jwt = false

[functions.analyze-bill-ai]
verify_jwt = false

[functions.explain-cpt]
verify_jwt = false

[functions.import-pricing-csv]
verify_jwt = false

[functions.process-cms-zip]
verify_jwt = false

[functions.fetch-cms-pricing]
verify_jwt = false

[functions.upload-bill]
verify_jwt = false
